export const USER_ME = 'USER_ME';
export const USER_ACTIVATION = 'USER_ACTIVATION';

export const MY_CALENDARS = 'MY_CALENDARS';
export const PARTICIPATING_CALENDARS = 'PARTICIPATING_CALENDARS';
export const CALENDAR_PARTICIPANTS = 'CALENDAR_PARTICIPANTS';
export const CALENDAR_INVITATIONS = 'CALENDAR_INVITATIONS';

export const MY_CALENDAR_INVITATIONS = 'MY_CALENDAR_INVITATIONS';

export const EVENTS = 'EVENTS';
export const EVENTS_INVITATIONS = 'EVENTS_INVITATIONS';
export const MY_EVENTS_INVITATIONS = 'MY_EVENTS_INVITATIONS';
export const COUNTRY_CODE = 'COUNTRY_CODE';
export const USER_LOCATION = 'USER_LOCATION';
